[package]
name = "conjugita"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
ron = "0.8.1"
serde_json = "1.0.121"
clap = { version = "4.5.13", features = ["derive"] }
seal = "0.1.5"
colored = "2.1.0"
